package com.justdrop.app.service

import android.app.*
import android.content.Intent
import android.content.pm.ServiceInfo
import android.os.Build
import android.os.IBinder
import android.util.Log
import androidx.core.app.NotificationCompat
import androidx.core.app.ServiceCompat
import com.justdrop.app.JustBridge
import com.justdrop.app.JustDropApp
import com.justdrop.app.ble.BleAdvertiser
import com.justdrop.app.ble.BleGattServer
import com.justdrop.app.ble.BleScanner

/**
 * Foreground service running the JustDrop engine with BLE discovery.
 *
 * Manages:
 * - Rust engine lifecycle
 * - BLE advertising + scanning
 * - GATT server for handshake
 * - mDNS multicast lock
 */
class JustDropForegroundService : Service() {

    companion object {
        private const val TAG = "JustDropFgService"
        private const val NOTIFICATION_ID = 1
        private const val CHANNEL_ID = "justdrop_service"
    }

    private var multicastLock: android.net.wifi.WifiManager.MulticastLock? = null
    private lateinit var bleAdvertiser: BleAdvertiser
    private lateinit var bleScanner: BleScanner
    private lateinit var gattServer: BleGattServer

    override fun onCreate() {
        super.onCreate()
        Log.i(TAG, "Service created")
        JustDropApp.isServiceRunning = true

        createNotificationChannel()
        startForegroundNotification()

        bleAdvertiser = BleAdvertiser(this)
        bleScanner = BleScanner(this)
        gattServer = BleGattServer(this)

        acquireMulticastLock()
        initRustEngine()
        startBle()
    }

    override fun onStartCommand(intent: Intent?, flags: Int, startId: Int): Int {
        return START_STICKY
    }

    override fun onBind(intent: Intent?): IBinder? = null

    override fun onDestroy() {
        Log.i(TAG, "Service destroyed")
        JustDropApp.isServiceRunning = false

        bleAdvertiser.stop()
        bleScanner.stop()
        gattServer.stop()

        multicastLock?.release()
        multicastLock = null

        JustBridge.shutdown()
        super.onDestroy()
    }

    private fun createNotificationChannel() {
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.O) {
            val channel = NotificationChannel(
                CHANNEL_ID,
                "JustDrop Service",
                NotificationManager.IMPORTANCE_LOW,
            ).apply {
                description = "JustDrop file transfer service"
                setShowBadge(false)
            }
            getSystemService(NotificationManager::class.java)
                .createNotificationChannel(channel)
        }
    }

    private fun startForegroundNotification() {
        val notification = NotificationCompat.Builder(this, CHANNEL_ID)
            .setContentTitle("JustDrop")
            .setContentText("Ready to send and receive files")
            .setSmallIcon(android.R.drawable.ic_menu_share)
            .setPriority(NotificationCompat.PRIORITY_LOW)
            .setOngoing(true)
            .build()

        val type = if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.Q) {
            ServiceInfo.FOREGROUND_SERVICE_TYPE_DATA_SYNC or
                ServiceInfo.FOREGROUND_SERVICE_TYPE_CONNECTED_DEVICE
        } else 0

        ServiceCompat.startForeground(this, NOTIFICATION_ID, notification, type)
    }

    private fun acquireMulticastLock() {
        val wifi = applicationContext.getSystemService(android.content.Context.WIFI_SERVICE) as android.net.wifi.WifiManager
        multicastLock = wifi.createMulticastLock("JustDropMulticastLock").apply {
            setReferenceCounted(true)
            acquire()
        }
    }

    private fun initRustEngine() {
        val justDropDir = java.io.File(
            android.os.Environment.getExternalStorageDirectory(), "JustDrop"
        )
        if (!justDropDir.exists()) justDropDir.mkdirs()

        JustBridge.setDownloadsDir(justDropDir.absolutePath)
        JustBridge.setDataDir(filesDir.absolutePath)

        val result = JustBridge.init(null)
        if (result != 0) {
            Log.e(TAG, "Rust engine init failed: $result")
            return
        }

        val discResult = JustBridge.startDiscovery()
        if (discResult != 0) {
            Log.e(TAG, "Discovery start failed: $discResult")
            return
        }

        Log.i(TAG, "Rust engine initialized")
    }

    private fun startBle() {
        // Start BLE advertising with device identity payload
        // Payload is generated by the Rust engine
        val payload = ByteArray(20) // Placeholder; filled by engine
        bleAdvertiser.start(payload)

        // Start BLE scanning
        bleScanner.start(object : BleScanner.Listener {
            override fun onDeviceFound(address: String, rssi: Int, serviceData: ByteArray?) {
                Log.d(TAG, "BLE device found: $address rssi=$rssi")
                // Feed to Rust engine for peer discovery merge
            }

            override fun onDeviceLost(address: String) {
                Log.d(TAG, "BLE device lost: $address")
            }
        })

        // Start GATT server for handshake
        gattServer.start(object : BleGattServer.Listener {
            override fun onHandshakeReceived(deviceAddress: String, data: ByteArray): ByteArray? {
                Log.i(TAG, "Handshake from $deviceAddress: ${data.size} bytes")
                // Process via Rust engine crypto
                return null // Response generated by engine
            }

            override fun onDeviceConnected(deviceAddress: String) {
                Log.i(TAG, "GATT device connected: $deviceAddress")
            }

            override fun onDeviceDisconnected(deviceAddress: String) {
                Log.i(TAG, "GATT device disconnected: $deviceAddress")
            }
        })
    }
}
